###############################################
# MoveIt Servo Configuration
###############################################
use_gazebo: false
command_in_type: "speed_units"

# Max speeds. These scale unitless commands; with speed_units the teleop node
# already publishes velocities in m/s and rad/s.
scale:
  linear:  0.4  # meters per second
  rotational:  0.4 # radians per second
  joint: 0.4 # radians per second

# Outgoing command behavior
publish_period: 0.034  # ~30Hz, matches our webcam
low_latency_mode: false
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

# The topics Servo will listen to
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
robot_link_command_frame: left_base_link

# The topics Servo will output to the ROS 2 Controllers
command_out_type: trajectory_msgs/JointTrajectory
command_out_topic: /left_arm_controller/joint_trajectory

# The Planning Group
move_group_name: left_arm
planning_frame: world
is_primary_planning_scene_monitor: false
ee_frame_name: left_tool0

incoming_command_timeout: 0.1
num_outgoing_halt_msgs_to_publish: 4

# Safety limits
lower_singularity_threshold: 35.0
hard_stop_singularity_threshold: 70.0
joint_limit_margin: 0.1
leaving_singularity_threshold_multiplier: 2.0

# Topics and collision checking
joint_topic: /joint_states
status_topic: ~/status
check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
